#!/usr/bin/env python3
"""Upload a Lean Inventory project to Firebase via the firebase-data wrapper.

KPH Sales OS — generated by lean-project-onboarding skill.

Run from Liam's Mac terminal (NOT from Cowork or Claude Code sandbox — egress is blocked):
    python3 upload_v1.py

Required:
- ~/.kph_admin_token must contain a valid Bearer token (the file should include the literal "Bearer " prefix)
- 4 PING1 images at the paths configured below
- Firebase payload in the PROJECT_PAYLOAD block below

Known issues this script handles:
- Cloudflare error 1010: Sets Mozilla User-Agent so Cloudflare doesn't block as bot
- KPR-92 (open): Detects "Firebase app does not exist" 500 errors and reports them
- Token expiration (KPR-50): Detects 401 and points user to refresh procedure
"""

import base64
import json
import mimetypes
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

# ============================================================
# CONFIGURATION — fill these in for your project
# ============================================================

PROJECT_ID = "KP-RSL-XXX"          # e.g., "KP-RSL-002"
PROJECT_NAME = "ProjectName"        # e.g., "VillaAnne" (no spaces)
CUSTOMER_ID = "11a3a8c9-d3db-4b32-8c08-35dd7868b959"

# Image paths — relative to the project's reference/images/{ProjectName}/ folder
PROJECT_FOLDER = Path.home() / "Business" / "01_Real-Estate-Leads" / "Campaigns" / f"{PROJECT_ID}_{PROJECT_NAME}"
IMAGES_FOLDER = PROJECT_FOLDER / "reference" / "images" / PROJECT_NAME

PING1_IMAGES = [
    # (filename in IMAGES_FOLDER, image_id for Firebase)
    ("01_hero_exterior.jpg", f"KP-IMG-{PROJECT_ID.split('-')[1]}-{PROJECT_ID.split('-')[2]}-PING1-01"),
    ("02_hero_pool.jpg",      f"KP-IMG-{PROJECT_ID.split('-')[1]}-{PROJECT_ID.split('-')[2]}-PING1-02"),
    ("03_bedroom_master.jpg", f"KP-IMG-{PROJECT_ID.split('-')[1]}-{PROJECT_ID.split('-')[2]}-PING1-03"),
    ("04_living.jpg",         f"KP-IMG-{PROJECT_ID.split('-')[1]}-{PROJECT_ID.split('-')[2]}-PING1-04"),
]

# Project payload — fill from your filled firebase_payload_resale.json template
# The script will inject created_at, updated_at, last_updated_public, and first_message_media_urls
# at runtime.
PROJECT_PAYLOAD = {
    # ... paste filled payload here ...
}

# ============================================================
# Constants — do not change
# ============================================================

API_BASE = "https://api.aiagentpro.online/api/firebase-data"
TOKEN_PATH = Path.home() / ".kph_admin_token"
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# ============================================================
# Helpers
# ============================================================

def load_token():
    if not TOKEN_PATH.exists():
        sys.exit(f"❌ Token file not found at {TOKEN_PATH}. Refresh per KPR-50 procedure.")
    token = TOKEN_PATH.read_text().strip()
    if not token.startswith("Bearer "):
        token = "Bearer " + token
    return token

def request(method, path, body=None):
    """Single HTTP helper. All requests go through here so the User-Agent is consistent."""
    url = f"{API_BASE}/{path}?customerId={CUSTOMER_ID}"
    headers = {
        "Authorization": TOKEN,
        "Content-Type": "application/json",
        "User-Agent": USER_AGENT,
    }
    data = None
    if body is not None:
        data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.status, resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        return e.code, body_text
    except urllib.error.URLError as e:
        return 0, f"NETWORK_ERROR: {e}"

def diagnose_error(status, response_text):
    """Map common errors to actionable advice."""
    if status == 401:
        return "TOKEN EXPIRED (KPR-50). Refresh from app.aiagentpro.online > DevTools console:\n   JSON.parse(localStorage.getItem('auth-storage')).state.token"
    if status == 403 and "1010" in response_text:
        return "CLOUDFLARE BLOCKED (error 1010). User-Agent should already be set — check this script."
    if status == 403:
        return "FORBIDDEN. Possibly running from Cowork sandbox (egress blocked). Run from Mac terminal."
    if status == 500 and "default Firebase app does not exist" in response_text:
        return "KPR-92 OPEN BUG — server-side Firebase init failure. Adam needs to fix. Workaround: manual upload via app.aiagentpro.online/dashboard"
    if status == 0:
        return f"NETWORK ERROR. Check internet connection. {response_text}"
    return None

def encode_image_to_base64(path):
    if not path.exists():
        sys.exit(f"❌ Image not found: {path}")
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")

def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")

def now_date():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")

# ============================================================
# Main flow
# ============================================================

print("=" * 70)
print(f"Upload {PROJECT_ID} → Firebase")
print("=" * 70)

TOKEN = load_token()

if not IMAGES_FOLDER.exists():
    sys.exit(f"❌ Images folder not found: {IMAGES_FOLDER}")

# --- STEP 1: Upload 4 PING1 images ---
print("\n" + "=" * 70)
print("STEP 1 — Upload 4 PING1 images")
print("=" * 70)

image_results = []
total_bytes = 0

for sort_order, (filename, image_id) in enumerate(PING1_IMAGES, start=1):
    image_path = IMAGES_FOLDER / filename
    image_b64 = encode_image_to_base64(image_path)
    mime, _ = mimetypes.guess_type(filename)
    if not mime:
        mime = "image/jpeg"
    size = image_path.stat().st_size
    total_bytes += size

    payload = {
        "_id": image_id,
        "image_id": image_id,
        "project_id": PROJECT_ID,
        "customerId": CUSTOMER_ID,
        "file_name": filename,
        "filename": filename,
        "mime_type": mime,
        "is_ping1": True,
        "is_primary": (sort_order == 1),
        "sort_order": sort_order,
        "image_data": image_b64,
        "uploaded_at": now_iso(),
    }

    status, body = request("PUT", f"Project_Images/{image_id}", body=payload)
    print(f"  PUT  {image_id}  [{size:,} bytes]  →  HTTP {status}")
    if status != 200:
        diag = diagnose_error(status, body)
        if diag:
            print(f"     >>> {diag}")
        print(f"     response: {body[:300]}")

    # Verify with GET
    g_status, g_body = request("GET", f"Project_Images/{image_id}")
    verified = (g_status == 200 and image_id in g_body)
    print(f"  GET  {image_id}  →  HTTP {g_status}  verified={verified}")

    image_results.append({
        "image_id": image_id,
        "put_status": status,
        "get_status": g_status,
        "verified": verified,
        "size": size,
    })

# Inject image IDs into project payload
PROJECT_PAYLOAD["first_message_media_urls"] = [img_id for _, img_id in PING1_IMAGES]
PROJECT_PAYLOAD["created_at"] = now_iso()
PROJECT_PAYLOAD["updated_at"] = now_iso()
PROJECT_PAYLOAD["last_updated_public"] = now_date()

# --- STEP 2: Create /Projects_Public/{PROJECT_ID} ---
print("\n" + "=" * 70)
print(f"STEP 2 — Create /Projects_Public/{PROJECT_ID}")
print("=" * 70)

p_status, p_body = request("PUT", f"Projects_Public/{PROJECT_ID}", body=PROJECT_PAYLOAD)
print(f"  PUT  /Projects_Public/{PROJECT_ID}  →  HTTP {p_status}")
if p_status != 200:
    diag = diagnose_error(p_status, p_body)
    if diag:
        print(f"    >>> {diag}")
    print(f"    response: {p_body[:500]}")

g_status, g_body = request("GET", f"Projects_Public/{PROJECT_ID}")
print(f"  GET  /Projects_Public/{PROJECT_ID}  →  HTTP {g_status}")

# --- STEP 3: Verification snapshot ---
print("\n" + "=" * 70)
print("STEP 3 — Verification snapshot (key fields)")
print("=" * 70)

if g_status == 200:
    try:
        data = json.loads(g_body)
        for field in ["_id", "project_id", "project_name", "property_type", "campaign_status",
                      "status", "location_area", "bedrooms", "bathrooms", "price_range_thb",
                      "has_pool", "pool_type", "rental_active", "first_message_media_urls"]:
            v = data.get(field, "<MISSING>")
            print(f"  {field}: {v}")
        opts = data.get("purchase_options", [])
        print(f"  purchase_options count: {len(opts)}")
    except json.JSONDecodeError:
        print(f"  ❌ Could not parse response: {g_body[:300]}")
else:
    print("  ❌ GET failed — cannot verify")

# --- SUMMARY ---
print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)

verified = sum(1 for r in image_results if r["verified"])
print(f"Images verified: {verified}/{len(PING1_IMAGES)}")
print(f"Total image bytes uploaded: {total_bytes:,}")
print(f"Project record: {'✅ CREATED + VERIFIED' if g_status == 200 else 'FAILED'}")

for r in image_results:
    status_icon = "✅" if r["verified"] else "✗"
    print(f"  {status_icon} {r['image_id']}  PUT={r['put_status']}  GET={r['get_status']}  size={r['size']:,}B")

# Exit code
if verified == len(PING1_IMAGES) and g_status == 200:
    print("\n🎉 SUCCESS — project is live in Firebase.")
    sys.exit(0)
else:
    print("\n⚠️  PARTIAL or FAILED — review errors above.")
    sys.exit(1)
